DEVICE_PATH := device/oppo/findx9

include $(DEVICE_PATH)/configs/BoardConfigTwrp.mk

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_VARIANT := generic
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_SUPPORTS_64_BIT_APPS := true

TARGET_BOARD_PLATFORM := mt6993
TARGET_BOARD_PLATFORM_GPU := immortalis

# Find X9 PLJ110 / OP5E17L1 uses the MT6993 k6993v1_64 GKI-derived 6.12 kernel.
TARGET_KERNEL_CONFIG := mgk_64_k612_defconfig
TARGET_KERNEL_SOURCE := android_kernel_modules_and_devicetree_oppo_mt6993/kernel/kernel_device_modules-6.12

BOARD_BOOT_HEADER_VERSION := 4
BOARD_VENDOR_BOOT_HEADER_VERSION := 4
BOARD_USES_GENERIC_KERNEL_IMAGE := true
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true
BOARD_INCLUDE_RECOVERY_DTBO := true

# Exact by-name block sizes from PLJ110 slot _b.
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 100663296
BOARD_DTBOIMG_PARTITION_SIZE := 25165824
BOARD_SUPER_PARTITION_SIZE := 0

BOARD_FLASH_BLOCK_SIZE := 4096
BOARD_KERNEL_PAGESIZE := 4096
BOARD_KERNEL_IMAGE_NAME := Image

BOARD_HAS_LARGE_FILESYSTEM := true
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

TW_THEME := portrait_hdpi
TW_DEVICE_VERSION := Find X9-PLJ110
TW_EXTRA_LANGUAGES := true
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_CRYPTO_FBE := true
TW_INCLUDE_F2FS_UTILS := true
TW_INCLUDE_NTFS_3G := true
TW_INCLUDE_FUSE_EXFAT := true
TW_USE_TOOLBOX := true
TW_INPUT_BLACKLIST := hbtp_vm

# There is no standalone recovery by-name partition. Recovery belongs in vendor_boot.
TARGET_NO_RECOVERY := true
